---
# tasks file for grafana

---
# tasks file for Grafana

- block:

  ############# pre Debian 12 requirement
  - name: "Prepare the apt keyring directory"
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
    become: true

  - name: "Get the grafana gpg key used for Grafana and grafana"
    ansible.builtin.shell:
      cmd: "wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg"
    become: true

  - name: "setup Grafana apt repo"
    ansible.builtin.copy:
      src: grafana.list
      dest: /etc/apt/sources.list.d/grafana.list
    become: true

  - name: "Install Grafana OSS package"
    ansible.builtin.apt:
      update_cache: true
      pkg:
        - grafana
    become: true

  - name: Template config to  /etc/Grafana/config.yml
    ansible.builtin.template:
      src: client_config.yml.j2
      dest: /etc/Grafana/config.yml
    become: true

  - name: systemd reload configs and restart Grafana
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: grafana-server
      state: restarted
      enabled: true
    become: true

  when: grafana_state == 'present'


- block:

  - name: "Remove Grafana package"
    ansible.builtin.apt:
      update_cache: true
      pkg:
        - grafana
      autoremove: true
      autoclean: true
      state: absent
    become: true

  - name: "Remove the config file"
    ansible.builtin.file:
      path: /etc/Grafana/config.yml
      state: absent
    become: true

  when: grafana_state == 'absent'