---

- name: Install basic packages (more later)
  hosts: serenity
  
  tasks:
  
  - name: "Install Basic Packages"
    ansible.builtin.dnf:
      name:
      - vim
      - tree
      - curl
      - socat
      - sudo
      - gpg
      - wget
      - ca-certificates 
      - net-tools
    become: true
