---

- name: Podman Installation
  hosts: localhost
  connection: local

  tasks:

    - ansible.builtin.debug:
        var: telegraf_influx_url

    - ansible.builtin.debug:
        var: telegraf_influx_token

    - ansible.builtin.debug:
        var: promtail_loki_url

    - ansible.builtin.debug:
        var: cluster_nfs_mounts
