---

- name: first run
  hosts: 127.0.0.1
  connection: local

  vars:
    monitor_ip: 127.0.0.1

  tasks:
  
  - name: "Basic packages with docker"
    ansible.builtin.apt:
      pkg:
      - wireguard
      - vim
      - tree
      - curl
      - socat
      - wireguard
      - sudo
      - gpg
      - apt-transport-https
      - software-properties-common
      - wget
      - net-tools
      - arping

        #sudo install -m 0755 -d /etc/apt/keyrings
        #sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
        #sudo chmod a+r /etc/apt/keyrings/docker.asc


  - name: "Prepare the apt keyring directory"
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: 0755

  - name: "Get the grafana gpg key used for promtail and grafana"
    ansible.builtin.shell:
      cmd: "curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc"
  - name "set permission on the key"
    ansible.builtin.file:
      path: /etc/apt/keyrings/docker.asc
      mode: 0644


  ##################        
  - name: "Get  keyring"
    ansible.builtin.shell:
      cmd: "curl -fsSL https://repos.influxdata.com/influxdata-archive_compat.key -o /etc/apt/keyrings/influxdata-archive_compat.key "
  - name: "setup telegraf apt repo"
    ansible.builtin.shell:
      cmd: echo "deb [signed-by=/etc/apt/keyrings/influxdata-archive_compat.key] https://repos.influxdata.com/debian stable main" | tee /etc/apt/sources.list.d/influxdata.list

