---

- name: Quiet rtkit logs
  hosts: 127.0.0.1
  connection: local

  tasks:
  
  - name: Create the directory if it does not exist
    ansible.builtin.file:
      path: /etc/systemd/system/rtkit-daemon.service.d/
      state: directory
      mode: '0755'

  - name: Copy conf file 
    ansible.builtin.copy:
      src: files/rtkit-override.conf
      dest: /etc/systemd/system/rtkit-daemon.service.d/override.conf
      owner: root
      group: root
      mode: '0644'

  - name: Restart rtkit-daemon.service
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true
      name: rtkit-daemon.service

