---

- name: first run
  hosts: localhost
  connection: local

  tasks:

  - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
    community.crypto.openssh_keypair:
      path: "~/.ssh/id_rsa"
      mode: '0600'

  - name: Generate an OpenSSH keypair with the default values (ed25519)
    community.crypto.openssh_keypair:
      path: "~/.ssh/id_ed25519"
      type: ed25519
      mode: '0600'
