---

##
#
# Install the required packages
#

- name: "Required Packages"
  ansible.builtin.apt:
    update_cache: true
    pkg:
    - git
  become: true

##
#  Download
#

- name: Download Godea Version 1.22.3
  ansible.builtin.get_url:
    url: https://dl.gitea.com/gitea/1.22.3/gitea-1.22.3-linux-amd64
    dest: /usr/local/bin/gitea1
    mode: '0755'
  become: true


##
#  Create Gidea user
#

- name: Ensure group "git" exists
  ansible.builtin.group:
    name: git
    system: true
    state: present
  become: true

- name: Add the user 'git' with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: git
    group: git
    comment: 'Git Version Control'
    home: /home/git
    system: yes
    password: "!"
    shell: /bin/bash
  become: true

##
#
#  Build the file structure
#

- name: Build data directories
  ansible.builtin.file:
    path: /var/lib/gitea
    owner: git
    group: git
    mode: '0750'
    state: directory
  become: true

- name: "Next level directories"
  ansible.builtin.file:
    path: "/var/lib/gitea/{{ item }}"
    mode: '0750'
  with_list:
    - custom
    - data
    - log
  become: true


- name: Build etc
  ansible.builtin.file:
    path: /etc/gitea
    owner: root
    group: git
    mode: '0750'
    state: directory
  become: true


##
#  Prepare the Daemon
#

- name: Copy systemd file in to place
  ansible.builtin.copy:
    src: gitea.service
    dest: /etc/systemd/system/gitea.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Enable service and start
  ansible.builtin.systemd_service:
    state: started
    name: gitea
    enabled: true
    daemon_reload: true
  become: true
