---
# tasks file for nfs-client

- name: Install NFS client packages
  ansible.builtin.apt:
    update_cache: true
    pkg:
    - nfs-common
  become: true

- name: Mount an NFS volume
  ansible.posix.mount:
    src: 192.168.40.14:/lavnet-migration-2024 
    path: /mnt/homee_migration
    opts: rw,noatime,bg,rsize=131072,wsize=131072,hard,intr,timeo=150,retrans=3
    state: ephemeral
    fstype: nfs4

#192.168.40.14:/lavnet-migration-2024 /mnt/homee_migration nfs4 rw,noatime,bg,rsize=131072,wsize=131072,hard,intr,timeo=150,retrans=3