---
# tasks file for loki

- block:

  ############# pre Debian 12 requirement
  - name: "Prepare the apt keyring directory"
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
    become: true

  - name: "Get the Grafana-Loki gpg key used for Grafana and grafana"
    ansible.builtin.shell:
      cmd: "wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg"
    become: true

  - name: "setup Grafana-Loki apt repo"
    ansible.builtin.copy:
      src: grafana.list
      dest: /etc/apt/sources.list.d/grafana.list
    become: true

  - name: "Install Loki OSS package"
    ansible.builtin.apt:
      update_cache: true
      pkg:
        - loki
    become: true




  - name: Template config to  /etc/loki/config.yml
    ansible.builtin.template:
      src: server-config.yml.j2
      dest: /etc/loki/config.yml
    become: true

  - name: systemd reload configs and restart Loki
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: loki
      state: restarted
      enabled: true
    become: true

  when: loki_state == 'present'


- block:

  - name: "Remove Loki package"
    ansible.builtin.apt:
      update_cache: true
      pkg:
        - loki
      autoremove: true
      autoclean: true
      state: absent
    become: true

  - name: "Remove the config file"
    ansible.builtin.file:
      path: /etc/loki/config.yml
      state: absent
    become: true

  when: loki_state == 'absent'