---
# tasks file for telegraf

############# pre Debian 12 requirement
- name: "Prepare the apt keyring directory"
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: "Get telegraf keyring"
  ansible.builtin.get_url:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    dest: /etc/apt/keyrings/influxdata-archive_compat.key

- name: "setup telegraf apt repo"
  ansible.builtin.copy:
    src: influxdata.list
    dest: /etc/apt/sources.list.d/influxdata.list

- name: "Install Telegraf via Package"
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - telegraf

- name: copy telegraf.d configuration files
  ansible.builtin.copy:
    src: telegraf.d
    dest: /etc/telegraf.d

- name: copy default systemd conf file
  ansible.builtin.copy:
    src: etc_default_telegraf
    dest: /etc/telegraf.conf

- name: systemd reload configs and restart promtail
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: telegraf
    state: restarted
    enabled: true



